version: "3.4"

networks:
  dev:
    driver: bridge

services:
  bookit.api:
    image: bookitapi
    container_name: Bookit.Api
    build:
      context: .
      dockerfile: Bookit.Api/Dockerfile
    depends_on:
      - bookit-database
    environment:
      - ConnectionStrings__Default=Server=bookit-database;Port=5432;Database=bookit-database;Username=postgres;Password=postgres;Integrated Security=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8088:80"
    networks:
      - dev

  bookit-database:
    image: postgres:latest
    container_name: Bookit.Database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookit-database
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
    ports:
      - "5432:5432"
    restart: always

  bookit-idp:
    image: quay.io/keycloak/keycloak:22.0.3
    command: start-dev --import-realm --hostname-debug=true
    restart: always
    container_name: Bookit.Identity
    depends_on:
      - bookit-database
    environment:
      DB: bookit-database
      DB_URL: jdbc:postgresql://bookit-database:5432/bookit-database
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/bookit-realm-export.json
    volumes:
      - app_data:/opt/keycloak/standalone/data
      - ./.files/bookit-realm-export.json:/opt/keycloak/data/import/bookit-realm-export.json
    ports:
      - 18080:8080
    networks:
      - dev

volumes:
  app_data:
