version: "3.4"

services:
  bookit.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - 5001:443
    volumes:
      - ~/.microsoft/usersecrets/UserSecrets:/root/.microsoft/usersecrets:ro
      - ~/.microsoft/ASP.NET/Https:/root/.aspnet/https:ro
